nameOverride: ""
replicas: "1"
podAnnotations: {}
hostNetwork: "false"
dnsPolicy: "ClusterFirst"
image:
  repository: registry.cn-hangzhou.aliyuncs.com/originx/apo-front
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi
service:
  type: NodePort
  nodePort: 31364
config:
  apoJaegerCollectorUrl: "http://apo-jaeger-collector-svc:16686"
  apoGrafanaUrl: "http://apo-grafana-svc:80"
  apoBackendUrl: "http://apo-backend-svc:8080" 

nodeSelector: {}
tolerations: []
affinity: {}
