apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apo-one-agent.fullname" . }}
  labels:
    {{- include "apo-one-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "networking.k8s.io"
    resources:
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
      - pods/status
      - events
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "monitoring.grafana.com"
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets/finalizers
      - deployments/finalizers
      - statefulsets/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets/status
      - deployments/status
      - statefulsets/status
    verbs:
      - get
  - apiGroups:
      - odigos.io
    resources:
      - collectorsgroups
      - destinations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - odigos.io
    resources:
     - instrumentedapplications
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - odigosconfigurations
      - destinations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - odigos.io
    resources:
      - instrumentedapplications/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - odigos.io
    resources:
     - instrumentationinstances
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - odigos.io
    resources:
      - instrumentationinstances/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - "replicasets"
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apo-one-agent.fullname" . }}
  labels:
    {{- include "apo-one-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apo-one-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "apo-one-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
