apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "apo"
spec:
  configuration:
    users:
      # admin use has 'password_sha256_hex' so actual password value is not published
      admin/password: "{{ tpl .Values.clickhouse.password . }}"
      admin/networks/ip: "::/0"
    clusters:
      - name: "clickhouse"
        templates:
          podTemplate: apo-clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
{{- if .Values.clickhouse.persistence.enabled  }}
  templates:
    podTemplates:
      - name: apo-clickhouse
        spec:
          containers:
            - name: clickhouse
              image: "{{ tpl .Values.clickhouse.image.repository . }}:23.8"
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server

    # volumeClaimTemplates:
    #   - name: data-storage-vc-template
    #     reclaimPolicy: Retain
    #     spec:
    #       accessModes:
    #         - ReadWriteOnce
    #       resources:
    #         requests:
    #           storage: 16Gi
    #   - name: log-storage-vc-template
    #     reclaimPolicy: Retain
    #     spec:
    #       accessModes:
    #         - ReadWriteOnce
    #       resources:
    #         requests:
    #           storage: 1Gi
    
    volumeClaimTemplates:
      - name: data-storage-vc-template
        reclaimPolicy: Retain
        spec:
          accessModes:
{{ toYaml .Values.clickhouse.persistence.data.accessModes | indent 12 }}
          resources:
            requests:
              storage: "{{ .Values.clickhouse.persistence.data.size }}"
        {{- if .Values.clickhouse.persistence.data.storageClass }}
        {{- if (eq "" (tpl .Values.clickhouse.persistence.data.storageClass .)) }}
        {{- else }}
          storageClassName: "{{ tpl .Values.clickhouse.persistence.data.storageClass . }}"
        {{- end }}
        {{- end }}
        {{- with .Values.clickhouse.persistence.data.matchLabels }}
          selector:
            matchLabels:
              {{- toYaml . | nindent 12 }}
        {{- end }}
      - name: log-storage-vc-template
        reclaimPolicy: Retain
        spec:
          accessModes:
{{ toYaml .Values.clickhouse.persistence.log.accessModes | indent 12 }}
          resources:
            requests:
              storage: "{{ .Values.clickhouse.persistence.log.size }}"
        {{- if .Values.clickhouse.persistence.log.storageClass }}
        {{- if (eq "" (tpl .Values.clickhouse.persistence.log.storageClass .)) }}
        {{- else }}
          storageClassName: "{{ tpl .Values.clickhouse.persistence.log.storageClass . }}"
        {{- end }}
        {{- end }}
        {{- with .Values.clickhouse.persistence.log.matchLabels }}
          selector:
            matchLabels:
              {{- toYaml . | nindent 12 }}
        {{- end }}
{{- else }}
  templates:
    podTemplates:
      - name: apo-clickhouse
        spec:
          containers:
            - name: clickhouse
              image: "{{ tpl .Values.clickhouse.image.repository . }}:23.8"
{{- end }}