apiVersion: v1
kind: ConfigMap
metadata:
  name: apo-clickhouse-init-apo-sql
data:
  init-apo.sh: |
    #!/bin/bash
    echo "开始创建数据库"
    set -e
    clickhouse client -n <<-EOSQL
      CREATE DATABASE IF NOT EXISTS apo;
    EOSQL
    echo "数据库创建完成"
