apiVersion: v2
name: apo-one-agent
version: "1.0.001"
appVersion: "1.0.0"
type: application
description: apo-one-agent deployment charts

dependencies:
  - name: apo-nginx-proxy
    condition: apo-nginx-proxy.enabled
    repository: "file://dep/apo-nginx-proxy"
  - name: apo-otel-collector
    condition: apo-otel-collector.enabled
    repository: "file://dep/apo-otel-collector"
  - name: odigos
    condition: odigos.enabled
    repository: "file://dep/odigos"