apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apo-front.fullname" . }}-nginx-config
  labels:
    {{- include "apo-front.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;

      access_log  /var/log/nginx/host.access.log  main;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      location /jaeger/ {
        proxy_pass {{ tpl .Values.config.apoJaegerCollectorUrl . }}/jaeger/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frame-Options "allow-from http://localhost:8080";
        proxy_buffering off;
      }

      location /grafana/ {
        proxy_pass {{ tpl .Values.config.apoGrafanaUrl . }}/grafana/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Frame-Options "allow-from http://localhost:8080";
        proxy_buffering off;
      }
      # 代理 API 请求到后端服务
      location /api/ {
          proxy_pass {{ tpl .Values.config.apoBackendUrl . }}/api/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
      }

      location /alert {
        rewrite ^/alert/(.*) /$1 break;
        proxy_pass http://apo-victoria-metrics-alert-server:8880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
      }

      #error_page  404              /404.html;

      # redirect server error pages to the static page /50x.html
      #
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }
