apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apo-front.fullname" . }}
  labels:
    {{- include "apo-front.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl (toString .Values.replicas) . }}
  selector:
    matchLabels:
      {{- include "apo-front.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apo-front.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: apo-front
        image: "{{ tpl .Values.image.repository . }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: apo-front-nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
      - name: apo-front-nginx
        configMap:
          name: {{ include "apo-front.fullname" . }}-nginx-config
          defaultMode: 420
