apiVersion: v1
kind: Service
metadata:
  name: apo-front-svc
  labels:
    {{- include "apo-front.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "apo-front.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}

