# Default values for camera-receiver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

initImage:
  repository: registry.cn-hangzhou.aliyuncs.com/kindlingx/busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.36.1"

apoCollector:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/originx/apo-collector
    pullPolicy: IfNotPresent
    tag: ""
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 1024Mi
  # requests:
  #   cpu: 512m
  #   memory: 512Mi
  service:
    type: NodePort
    port: 29090
    targetPort: 29090
    nodePortGrpc: 30044
    nodePortHttp: 30090
  config:
    victoriaMetricsUrl: "http://apo-victoria-metrics-single-server-svc:8428"
    clickhouseUrl: "apo-clickhouse-svc:9000"
    clickhouseUsername: "admin"
    clickhousePassword: "Apo@123456"
    apmAdapterUrl: "apo-apm-adapter-svc:8080"
    apoBackendUrl: "http://apo-backend-svc:8080"

apoApmAdapter:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/originx/apm-adapter
    pullPolicy: IfNotPresent
    tag: ""
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 1024Mi
  # requests:
  #   cpu: 512m
  #   memory: 512Mi
  service:
    port: 8079
  config:
    adapter:
      # 暴露HTTP端口号.
      http_port: 8079
      # 设置HTTP请求超时时间，超时则直接返回.
      timeout: 10
      # APM系统对接.
      trace_api:
        # 开启apm对接列表
        apm_list: [skywalking, jaeger, elastic]
        # Skywalking配置
        skywalking:
          address: ""
          user: ""
          password: ""
        # Jaeger配置
        jaeger:
          address: apo-jaeger-collector-svc:16686/jaeger
        # Tingyun3相关配置
        nbs3:
          address: ""
          user: ""
          password: ""
        # Arms相关配置
        arms:
          address: "arms.cn-hangzhou.aliyuncs.com"
          access_key: ""
          access_secret: ""
        elastic:
          # 可以添加协议前缀'https://'或'http://'，默认http
          address: ""
          user: ""
          password: ""
        # Pinpoint配置
        pinpoint:
          address: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



nodeSelector: {}

tolerations: []

affinity: {}

config:
  victoriaMetricsUrl: "http://apo-victoria-metrics-single-server-svc:8428"
  clickhouseUrl: "apo-clickhouse-svc:9000"
  clickhouseUsername: "admin"
  clickhousePassword: "Apo@123456"
  apmAdapterUrl: "http://apo-apm-adapter-svc:8079"
  apoBackendUrl: "http://apo-backend-svc:8080"