apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: apo-odigos-webhook-pod-configuration
webhooks:
  - name: mpod.kb.io
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: apo-odigos-webhook-svc
        path: /mutate-core-v1-pod
        port: 443
      caBundle: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVIVENDQXdXZ0F3SUJBZ0lVZURXd1FMVlZsSjQxampTZ1hCc0gxZkdLblU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZWXhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeQpZVzVqYVhOamJ6RVZNQk1HQTFVRUNnd01XVzkxY2lCRGIyMXdZVzU1TVJJd0VBWURWUVFMREFsWmIzVnlJRlZ1CmFYUXhKekFsQmdOVkJBTU1IbUZ3YnkxdlpHbG5iM010ZDJWaWFHOXZheTF6ZG1NdVlYQnZMbk4yWXpBZUZ3MHkKTkRBNE1EWXdOelF6TWpSYUZ3MHpOREE0TURRd056UXpNalJhTUlHR01Rc3dDUVlEVlFRR0V3SlZVekVMTUFrRwpBMVVFQ0F3Q1EwRXhGakFVQmdOVkJBY01EVk5oYmlCR2NtRnVZMmx6WTI4eEZUQVRCZ05WQkFvTURGbHZkWElnClEyOXRjR0Z1ZVRFU01CQUdBMVVFQ3d3SldXOTFjaUJWYm1sME1TY3dKUVlEVlFRRERCNWhjRzh0YjJScFoyOXoKTFhkbFltaHZiMnN0YzNaakxtRndieTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFSwpBb0lCQVFEbjdjUWQ3UDNkamR1dHBza0pMWFl1T25hSmFhaExqWTNSSHU0ay92MlBXK1hkR2RCelBzTmh0eE9nCjVjdm1VanV6c3gvZXdoUFBsbHZYaFVvRWdOVmFGVUExajhMN2xBU1hwZTVRaVh4M2RoaklqTE1TYk51d1piRWwKMlJXWVdXVUY1aEl0Z0NLdGNMbk5Tb0Q2K2pmTUtnYm5KSnBRanl3OStHK2xIM0VvK25Pa04rb0JoeUdvVjJKZgoveFRoRm52ZWdDWnlpcWxQSC9uTEJ6UjdCeEJwVUIxVlIyODhpRkVtdzJLRlJRVFhHcG1KaEsvWTJCdGJIblhPClFyVkhBZ0dEUDg2cC9nMkY2NTZ6R3U3KzNNemNnZmFvWG5iN2JHKzlaamxnMU1sKy8vQWpWa1RvbDZZdk9rVngKWE9pNVBRblJTSFpLT05hUUlISnViVGVjRnBuSkFnTUJBQUdqZ1lBd2ZqQmRCZ05WSFJFRVZqQlVnaFpoY0c4dApiMlJwWjI5ekxYZGxZbWh2YjJzdGMzWmpnaHBoY0c4dGIyUnBaMjl6TFhkbFltaHZiMnN0YzNaakxtRndiNEllCllYQnZMVzlrYVdkdmN5MTNaV0pvYjI5ckxYTjJZeTVoY0c4dWMzWmpNQjBHQTFVZERnUVdCQlRiK0xob05QaXcKRnJCTytLY2JuaUcrWHZpdEhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkQUJBSVpaWEdTbGFhWTI2Q05ZdgphQ3QrSnBVL3RvS1U3WnJqV1FxUUhKOXB6MUpjQmNNK3o4Nk81Y0pTc1Q3SStSYWF3WWdoWGlVUWM0emw5dHIzCmNCNkErM2s0aWVnd2V0QlZvRHBWY2dQOC85N1p6aEc4d2tuT2l3SzgvOUxGb0VUaXFlZmtLY2UyMXJhMndaYlkKWVZFZlVRMHVLVE50VGxHdnJzZFhCZTE5bit1aTJuRjlNWDN3ZWROZVZoaVFQRE4xaXBIOE5rYTNKeWFjdGJBcApvMXRZNk1USTQvVy84QkpEN01ld3N4OEZOZGZHZFRYWGljemZLTzd0WmJHV0IyQnE4RW1FdENKdWFqaTdGR0hpCk5CanVmU0VzTnYyT2ExS0pCMk4zRGJPZHJKWFZVTzlEenJ5K3RZelhJSDYzQkptRXdJWmtMQ24yQThNMGlpMHYKS3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations:
          - CREATE
        apiGroups:
          - ''
        apiVersions:
          - v1
        resources:
          - pods
        scope: '*'
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    sideEffects: None
    timeoutSeconds: 10
    admissionReviewVersions:
      - v1
    reinvocationPolicy: Never