image:
  tag: "v1.0.89"
  imagePullPolicy: IfNotPresent
imagePullSecrets: []

# namespaces not to show in odigos ui
ignoredNamespaces:
  - odigos-system
  - kube-system
  - local-path-storage
  - istio-system
  - linkerd
  - kube-node-lease

ignoredContainers:
  - istio-proxy

collectorGateway:
  # the memory request for the cluster gateway collector deployment.
  # it will be embedded in the deployment as a resource request
  # of the form "memory: <value>Mi".
  # default value is 500Mi
  requestMemoryMiB: 500
  # sets the "limit_mib" parameter in the memory limiter configuration for the collector gateway.
  # it is the hard limit after which a force garbage collection will be performed.
  # if not set, it will be 50Mi below the memory request.
  memoryLimiterLimitMiB: 450
  # sets the "spike_limit_mib" parameter in the memory limiter configuration for the collector gateway.
  # note that this is not the processor soft limit, but the diff in MiB between the hard limit and the soft limit.
  # if not specified, this value will be set to 20% of the hard limit (so the soft limit will be 80% of the hard limit).
  memoryLimiterSpikeLimitMiB: 90
  # the GOMEMLIMIT environment variable value for the collector gateway deployment.
  # this is when go runtime will start garbage collection.
  # if not specified, it will be set to 80% of the hard limit of the memory limiter.
  goMemLimitMiB: 340

autoscaler:
  image:
    repository: keyval/odigos-autoscaler
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

scheduler:
  image:
    repository: keyval/odigos-scheduler
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

ui:
  image:
    repository: keyval/odigos-ui
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

instrumentor:
  deleteLangDetectionPods: true
  image:
    repository: keyval/odigos-instrumentor
    imagePullPolicy: IfNotPresent
    tag: "v1.0.75-webhook"
  resources: {}
  #   limits:
  #     cpu: 500m
  #     memory: 128Mi
  #   requests:
  #     cpu: 10m
  #     memory: 64Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []
  # targetNamespace
  # name: Target namespace
  # value:
  #   enabled: Inject all existing services but do not inject newly added applications
  #   enabledFuture: Inject both current and future services
  #   disabled: Do not inject services in the specified namespace; used to exclude specific namespaces when instrument-all-namespace is enabled
  # targetNamespace:
  # - name: default
  #   value: disabled
  # instrument-all-namespace Whether to inject all namespaces
  # Equivalent to setting enabledFuture for all namespaces
  # However, if disabled is already set for a namespace or workload, it will not be injected
  instrumentAllNamespace: true
  # force-instrument-all-namespace Whether to force inject all namespaces
  # Similar to instrument-all-namespace, sets enabledFuture for all namespaces
  # Ignores all disabled settings
  forceInstrumentAllNamespace: false
  # enableOverwriteUserDefinedEnvs: Whether to overwrite user-defined environment variables
  enableOverwriteUserDefinedEnvs: false

odiglet:
  image:
    repository: keyval/odigos-odiglet
    enterpriseRepository: keyval/odigos-enterprise-odiglet
    imagePullPolicy: IfNotPresent
    tag: "v1.0.75-3"
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 128Mi
    # requests:
    #   cpu: 10m
    #   memory: 64Mi
  affinity: {}

config:
  apoOtelCollectorGrpcUrl: "apo-otel-collector-svc.apo:4317"
  apoOtelCollectorHttpUrl: "apo-otel-collector-svc.apo:4318"

cli:
  image:
    repository: keyval/odigos-cli

# Pod Security Policy
psp:
  enabled: false

telemetry:
  enabled: true

openshift:
  enabled: false

gke:
  enabled: false