nameOverride: ""
replicas: "1"
podAnnotations: {}
hostNetwork: "false"
dnsPolicy: "ClusterFirst"
podSecurityContext: {}
image:
  repository: docker.io/clouddetail/nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stable-alpine3.20"
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

serviceAccount:
  name: apo-otel-collector

service:
  ports:
  - name: apo-collector-grpc
    protocol: TCP
    port: 30044
    targetPort: 30044
  - name: apo-ilogtail-http
    protocol: TCP
    port: 30010
    targetPort: 30010
  type: ClusterIP

config:
  apoCollectorUrl: "localhost"
  apoCollectorPort: "29090"

nodeSelector: {}
affinity: {}
tolerations: []
