{{- if eq .Values.global.edition "ee" }}
apiVersion: v1
kind: Service
metadata:
  name: originx-root-cause-infer-svc
  labels:
    {{- include "originx-root-cause-infer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "originx-root-cause-infer.selectorLabels" . | nindent 4 }}
{{- end }}
