# {{- if .Values.enabled }}
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: apo-pre-delete-hook
#   labels:
#     app: apo-pre-delete-hook
#   annotations:
#     "helm.sh/hook": pre-delete
#     "helm.sh/hook-weight": "0"
#     "helm.sh/hook-delete-policy": "hook-succeeded"
# spec:
#   template:
#     metadata:
#       name: apo-pre-delete-hook
#       labels:
#         app: apo-pre-delete-hook
#     spec:
#       containers:
#         - name: delete-clickhouse-crd
#           image: "{{ .Values.global.image.repository }}/kubectl:1.30"
#           command:
#             - /bin/sh
#             - "-c"
#           args:
#             - kubectl delete clickhouseinstallation apo -n{{ .Release.Namespace }};
#       restartPolicy: Never
#       serviceAccountName: "apo-altinity-clickhouse-operator"
# {{- end }}