apiVersion: v2
name: apo-one-agent
version: "1.6.003"
appVersion: "1.6.1"
type: application
description: apo-one-agent deployment charts

dependencies:
  - name: apo-nginx-proxy
    condition: apo-nginx-proxy.enabled
    repository: ""
    version: '*.*.*'
  - name: apo-otel-collector
    condition: apo-otel-collector.enabled
    repository: ""
    version: '*.*.*'
  - name: odigos
    condition: odigos.enabled
    repository: ""
    version: '*.*.*'
