apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apo-otel-collector-gateway.fullname" . }}
  labels:
    {{- include "apo-otel-collector-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl (toString .Values.replicas) . }}
  selector:
    matchLabels:
      {{- include "apo-otel-collector-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apo-otel-collector-gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ tpl (toString .Values.hostNetwork) . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "apo-otel-collector-gateway.serviceAccountName" . }}
      {{- end }}
      initContainers:
      - name: check-clickhouse-ready
        image: "{{ tpl .Values.initImage.repository . }}:{{ tpl .Values.initImage.tag . }}"
        imagePullPolicy: {{ tpl .Values.initImage.pullPolicy . }}
        env:
        - name: CLICKHOUSE_URL
          value: {{ tpl .Values.global.clickhouseUrl . }}
        command:
        - sh
        - -c
        - |
          CLICKHOUSE_HOST=$(echo $CLICKHOUSE_URL | cut -d ':' -f 1)
          CLICKHOUSE_PORT=$(echo $CLICKHOUSE_URL | cut -d ':' -f 2)
          echo "等待 ${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT} clickhouse启动..."
          while ! nc -z ${CLICKHOUSE_HOST} ${CLICKHOUSE_PORT}; do
            echo "INFO: ClickHouse 还未启动成功。 将在5s后重新检查"
            sleep 5
          done
          echo "INFO: ClickHouse 启动成功"
      containers:
      - name: otel-collector
        image: "{{ tpl .Values.image.repository . }}:{{ tpl (toString (default .Chart.AppVersion .Values.image.tag)) . }}"
        imagePullPolicy: {{ tpl .Values.image.pullPolicy . }}
        command:
          - ./otelcol
          - '--config'
          - /app/conf/otelcol-config.yaml
        args:
          - >-
            --feature-gates=receiver.prometheusreceiver.RemoveLegacyResourceAttributes
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: collector-conf
            mountPath: /app/conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: collector-conf
        configMap:
          name: {{ include "apo-otel-collector-gateway.fullname" . }}-config
