{{- if eq .Values.server.configMap "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmalert.server.configname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "vmalert.server.labels" . | nindent 4 }}
data:
  alert-rules.yaml: |
    {{- if eq .Values.global.language "en" }}
    {{ toYaml .Values.server.config.alertsEn | nindent 4 }}
    {{- else if eq .Values.global.language "zh" }}
    {{ toYaml .Values.server.config.alertsZh | nindent 4 }}
    {{- end }}
{{- end }}