apiVersion: v1
kind: ConfigMap
metadata:
  name: apo-vmagent-config
  labels:
    {{- include "apo-one-agent.labels" . | nindent 4 }}
data:
  scrape.yml: |-
    global:
      scrape_interval: 60s
      external_labels:
        cluster_id: {{ .Values.global.clusterId | quote }}

    scrape_configs:
    - job_name: apo-one-agent
      scrape_interval: 30s
      static_configs:
        - targets: ["localhost:8429","localhost:9500","localhost:9499","localhost:9408"]
      relabel_configs:
        - action: replace
          source_labels: ["instance"]
          target_label: "instance_name"
        - action: replace
          source_labels: ["job"]
          target_label: "job_name"
    
    - job_name: integrations/unix
      static_configs:
        - targets: ["%{VM_MY_NODE_IP}:12345/api/v0/component/prometheus.exporter.unix.local_system/metrics"]
          labels:
              instance_name: "%{VM_HOSTNAME}"
      metric_relabel_configs:
        - action: replace
          source_labels: ["job"]
          target_label: "job_name"

    - job_name: "integrations/kubernetes/cadvisor"
      scheme: "https"
      scrape_interval: 60s
      bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets:
            - "%{VM_MY_NODE_IP}:10250"
          labels:
            node_name: "%{VM_HOSTNAME}"
      metrics_path: "/metrics/cadvisor"
      metric_relabel_configs:
        - action: replace
          source_labels: ["instance"]
          target_label: "instance_name"
        - action: replace
          source_labels: ["job"]
          target_label: "job_name"

    - job_name: "kubelet"
      scheme: "https"
      scrape_interval: 60s
      bearer_token_file: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets:
            - "%{VM_MY_NODE_IP}:10250"
          labels:
            node_name: "%{VM_HOSTNAME}"
      metric_relabel_configs:
        - action: replace
          source_labels: ["instance"]
          target_label: "instance_name"
        - action: replace
          source_labels: ["job"]
          target_label: "job_name"
