apiVersion: v1
kind: ConfigMap
metadata:
  name: apo-otel-collector-agent-config
  labels:
    {{- include "apo-one-agent.labels" . | nindent 4 }}
data:
  otelcol-config.yaml: |-
    extensions:
      fill_proc:
        enable: true
        interval: 5s
      pprof:
        endpoint: 0.0.0.0:1777
    receivers:
      prometheus/own_metrics:
        config:
          scrape_configs:
            - job_name: 'apo-otel-collector-agent'
              scrape_interval: 15s
              static_configs:
                - targets: ['0.0.0.0:1778']
      otlp:
        fillproc_extension: fill_proc
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 999999999
          http:
            endpoint: 0.0.0.0:4318
      signalfxgatewayprometheusremotewrite:
        endpoint: 0.0.0.0:4321
      skywalking:
        fillproc_extension: fill_proc
        protocols:
          grpc:
            endpoint: 0.0.0.0:11800 # Ingest Trace data reported by the SkyWalking Agent
          http:
            endpoint: 0.0.0.0:12800 # Ingest Trace data reported via HTTP protocol from frontend/nginx, etc.
    connectors:
      redmetrics:
        server_enabled: true
        db_enabled: true
        # Enable or disable HTTP/RPC outbound call metrics
        external_enabled: true
        # Enable or disable MQ middleware invocation metrics
        mq_enabled: true
        dimensions_cache_size: 1000
        max_services_to_track: 256
        max_operations_to_track_per_service: 2048
        metrics_flush_interval: 15s
        # vm(VictoriaMetrics) or prom(Promethues)
        metrics_type: "vm"
        # Promethues场景下需指定分桶.
        latency_histogram_buckets: [5ms, 10ms, 20ms, 30ms, 50ms, 80ms, 100ms, 150ms, 200ms, 300ms, 400ms, 500ms, 800ms, 1200ms, 3s, 5s, 10s, 15s, 20s, 30s, 40s, 50s, 60s]
        # URL aggregation algorithm: httpMethod / topUrl
        http_parser: topUrl
    processors:
      batch:
        send_batch_size: 5000
        timeout: 2s
      resource:
        attributes:
          - key: cluster_id
            value: {{ .Values.global.clusterId | quote }}
            action: insert
      backsampling:
        # Notify eBPF to collect OnOffMetric and Profile; set to 0 or leave unset to disable.
        {{- if eq .Values.global.edition "ee" }}
        ebpf_port: 9500
        {{- else }}
        ebpf_port: 0
        {{- end }}
        adaptive:
          enable: true
          span_slow_threshold: 10s
          service_sample_window: 5s
          service_sample_count: 1
          memory_check_interval: 2s
          memory_limit_mib_threshold: 500
          traceid_holdtime: 120s
        sampler:
          log_enable: true
          normal_top_sample: false
          normal_sample_wait_time: 60
          open_slow_sampling: true
          open_error_sampling: true
          enable_tail_base_profiling: true
          sample_trace_repeat_num: 3
          sample_trace_wait_time: 30
          sample_trace_ignore_threshold: 0
          sample_trace_slow_threshold_ms: 100
          silent_period: 15
          silent_count: 1
          silent_mode: window
        controller:
          host: "{{ tpl .Values.apoOtelCollectorAgent.config.apoCollectorUrl . }}"
          port: {{ tpl .Values.apoOtelCollectorAgent.config.apoCollectorPort . }}
          interval_query_slow_threshold: 30
          interval_query_sample: 2
          interval_send_trace: 1
        notify:
          enabled: true
    exporters:
      nop:
      debug:
        verbosity: normal
        sampling_initial: 5
        sampling_thereafter: 200
      otlp:
        endpoint: "http://{{ tpl .Values.apoOtelCollectorAgent.config.apoOtelCollectorUrl . }}:{{ tpl .Values.apoOtelCollectorAgent.config.apoOtelCollectorGRPCPort . }}"
        tls:
          insecure: true
        sending_queue:
          enabled: true
          num_consumers: 5
          queue_size: 100
    service:
      telemetry:
        logs:
          level: info
        metrics:
          level: basic
          address: ":1778"
        resource:
          node_name: "${MY_NODE_NAME}"
      extensions: [pprof, fill_proc]
      {{- if (has "trace-sidecar" .Values.global.agentCollectorMode) }}
      pipelines:
        traces:
          receivers: [otlp, skywalking]
          processors: [resource,batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [resource,batch]
          exporters: [otlp]
        metrics/sw:
          receivers: [skywalking]
          processors: []
          exporters: [nop]
        logs:
          receivers: [otlp]
          processors: [resource,batch]
          exporters: [otlp]
      {{- else }}
      pipelines:
        traces/red:
          receivers: [otlp, skywalking]
          processors: [batch]
          exporters: [redmetrics]
        traces:
          receivers: [otlp, skywalking]
          processors: [backsampling, batch]
          exporters: [otlp]
        metrics:
          receivers: [signalfxgatewayprometheusremotewrite, otlp, redmetrics, prometheus/own_metrics]
          processors: [batch]
          exporters: [otlp]
        metrics/sw:
          receivers: [signalfxgatewayprometheusremotewrite, skywalking]
          processors: []
          exporters: [nop]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
      {{- end }}
