apiVersion: v1
kind: ConfigMap
metadata:
  name: apo-ilogtail-user-config
  labels:
    {{- include "apo-one-agent.labels" . | nindent 4 }}
data:
  pod_stdout_file.yaml: |
    enable: false #默认禁用故障现场日志采集
    inputs:
      - Type: service_docker_stdout
        ExcludeK8sLabel:
          clickhouse.altinity.com/namespace: apo
          app.kubernetes.io/instance: apo
        BeginLineCheckLength: 10 # 新增配置
        BeginLineRegex: "\\d+.*" # 新增配置
    processors:
      - Type: processor_log_to_prom_metric
        PromPort: ":9499"
      - Type: processor_wait_for_signal
        ContentsRename:
          "__tag__:_container_id_": "_container_id_"
          "__tag__:__path__": "_source_"
    flushers:
      # - Type: flusher_stdout    # 标准输出流输出类型
      #   OnlyStdout: true
      - Type: flusher_http  #统一走vector入库
        RemoteURL: http://{{ tpl .Values.apoIlogtail.apoVectorLogUrl . }}
        Convert:
          Protocol: custom_single
          Encoding: json
  {{- if (has "log" .Values.global.agentCollectorMode) }}
  pod_stdout_all.yaml: |
    enable: true
    inputs:
      - Type: service_docker_stdout
        ExcludeK8sLabel:
          clickhouse.altinity.com/namespace: apo
          app.kubernetes.io/instance: apo
        BeginLineCheckLength: 10
        BeginLineRegex: "\\d+.*"
    processors:
      - Type: processor_log_to_prom_metric
        PromPort: ":9499"
      - Type: processor_wait_for_signal
        DisableSignalSampler: true
        ContentsRename:
          "__tag__:_container_id_": "_container_id_"
          "__tag__:__path__": "_source_"
    flushers:
      - Type: flusher_http
        RemoteURL: http://{{ tpl .Values.apoIlogtail.apoVectorLogUrl . }}
        Convert:
          Protocol: custom_single
          Encoding: json
  {{- end }}
