apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apo-backend.fullname" . }}-config
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
data:
  apo.yml: |
    server:
      port: 8080
      access_token_expire_minutes: 15
      refresh_token_expire_hours: 48

    logger:
      level: DEBUG
      console_enable: true
      file_enable: true
      # 日志保存路径.
      file_path: "./logs/apo.log"
      # 日志保存个数.
      file_num: 10
      # 日志保存大小，单位MB.
      file_size_mb: 100

    database:
      # 数据库类型 sqllite / mysql
      connection: sqllite
      max_open: 10
      max_idle: 60
      max_life_second: 60
      sqllite:
        database: database/database-apo.db
      mysql:
        host: 127.0.0.1
        port: 3306
        database: demo
        username: ""
        password: ""
        charset: "utf8mb4"

    clickhouse:
      address: "{{ tpl .Values.config.clickhouseUrl . }}"
      username: {{ tpl .Values.config.clickhouseUsername . }}
      password: {{ tpl .Values.config.clickhousePassword . }}
      database: {{ .Values.global.clickhouse.database }}
      replication: {{ .Values.global.clickhouse.replication }}
      cluster: "{{ .Values.global.clickhouse.clusterName }}"

    kubernetes:
      auth_type: "serviceAccount"

    promethues:
    {{- if eq .Values.global.victoriaMetrics.mode "single" }}
      address: {{ .Values.global.victoriaMetrics.single.url }}
    {{- else if eq .Values.global.victoriaMetrics.mode "cluster" }}
      address: {{ .Values.global.victoriaMetrics.cluster.selectUrl }}
    {{- end }}
      # vm / prom
      storage: vm

    language:
      # 返回错误的语言，en - 英文，zh-cn: 简体中文.
      local: zh-cn
    meta_server:
      enable: true
      meta_source_config:
        accept_event_source:
          enable_accept_server: true
        querier:
          enable_query_server: true
        exporter:
          enable_fetch_server: true
    
    jaeger:
      address: "http://apo-jaeger-collector-svc:16686"

    deepflow:
      server_address: http://deepflow-server:20416
      # 不配置时默认采用clickhouse中的配置
      {{- if .Values.global.deepflow.enabled }}
      ch_address: "{{ tpl .Values.global.deepflow.clickhouse.address . }}"
      ch_username: "{{ tpl .Values.global.deepflow.clickhouse.username . }}"
      ch_password: "{{ tpl .Values.global.deepflow.clickhouse.password . }}"
      {{- else }}
      ch_address:
      ch_username:
      ch_password:
      {{- end }}

    user:
      anonymous_user:
        username: anonymous
        enable: {{ tpl .Values.config.anonymousUserEnabled . }}
        role: admin

    dify:
      url: http://apo-dify-api-svc:5001
      user: apo-backend
      api_keys:
        alert_check: app-x0mOJKUvhr35BOISSeNmsfXj
      flow_ids: 
        alert_check: dcfeddd2-d6e7-4dc4-a284-e48ab56bf6af
        alert_event_analyze: a2d4d3aa-3401-4393-859e-df051bdd5cd1
