apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apo-backend.fullname" . }}
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl (toString .Values.replicas) . }}
  selector:
    matchLabels:
      {{- include "apo-backend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "apo-backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ tpl (toString .Values.hostNetwork) . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      serviceAccountName: {{ include "apo-backend.fullname" . }}
      serviceAccount: {{ include "apo-backend.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: check-clickhouse-ready
        image: "{{ tpl .Values.initImage.repository . }}:{{ tpl .Values.initImage.tag . }}"
        imagePullPolicy: {{ tpl .Values.initImage.pullPolicy . }}
        env:
        - name: CLICKHOUSE_URL
          value: {{ .Values.global.clickhouse.host }}:{{ .Values.global.clickhouse.nativePort }}
        command:
        - sh
        - -c
        - |
          CLICKHOUSE_HOST=$(echo $CLICKHOUSE_URL | cut -d ':' -f 1)
          CLICKHOUSE_PORT=$(echo $CLICKHOUSE_URL | cut -d ':' -f 2)
          echo "等待 ${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT} clickhouse启动..."
          while ! nc -z ${CLICKHOUSE_HOST} ${CLICKHOUSE_PORT}; do
            echo "INFO: ClickHouse 连接失败。 将在5s后重新检查"
            sleep 5
          done
          echo "INFO: ClickHouse 连接测试通过"
      containers:
      - name: apo-backend
        image: "{{- include "apo-backend.image" . }}"
        imagePullPolicy: {{ tpl .Values.apoBackend.image.pullPolicy . }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
            {{- toYaml .Values.apoBackend.resources | nindent 12 }}
        volumeMounts:
        - name: apo-backend-config
          mountPath: /app/config/apo.yml
          subPath: apo.yml
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 6
      - name: polaris-analyzer
        image: "{{ tpl .Values.apoPolarisAnalyzer.image.repository . }}:{{ .Values.apoPolarisAnalyzer.image.tag }}"
        imagePullPolicy: {{ tpl .Values.apoBackend.image.pullPolicy . }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
        - name: PROMETHEUS_ADDRESS
          {{- if eq .Values.global.victoriaMetrics.mode "single" }}
          value: {{ .Values.global.victoriaMetrics.single.url }}
          {{- else if eq .Values.global.victoriaMetrics.mode "cluster" }}
          value: {{ .Values.global.victoriaMetrics.cluster.selectUrl }}
          {{- end }}
        - name: PROMETHEUS_STORAGE
          value: vm
        resources:
            {{- toYaml .Values.apoPolarisAnalyzer.resources | nindent 12 }}
        volumeMounts:
        - name: apo-backend-config
          mountPath: /app/config/
      volumes:
      - name: apo-backend-config
        configMap:
          name: {{ include "apo-backend.fullname" . }}-config
          defaultMode: 420
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- else if .Values.global.affinity }}
      {{- with .Values.global.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}