apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apo-backend.fullname" . }}
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ tpl (toString .Values.replicas) . }}
  selector:
    matchLabels:
      {{- include "apo-backend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "apo-backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ tpl (toString .Values.hostNetwork) . }}
      dnsPolicy: {{ tpl .Values.dnsPolicy . }}
      serviceAccountName: {{ include "apo-backend.fullname" . }}
      serviceAccount: {{ include "apo-backend.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: check-clickhouse-ready
        image: "{{ tpl .Values.initImage.repository . }}:{{ tpl .Values.initImage.tag . }}"
        imagePullPolicy: {{ tpl .Values.initImage.pullPolicy . }}
        env:
        - name: CLICKHOUSE_URL
          value: {{ tpl .Values.global.clickhouseUrl . }}
        command:
        - sh
        - -c
        - |
          CLICKHOUSE_HOST=$(echo $CLICKHOUSE_URL | cut -d ':' -f 1)
          CLICKHOUSE_PORT=$(echo $CLICKHOUSE_URL | cut -d ':' -f 2)
          echo "等待 ${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT} clickhouse启动..."
          while ! nc -z ${CLICKHOUSE_HOST} ${CLICKHOUSE_PORT}; do
            echo "INFO: ClickHouse 连接失败。 将在5s后重新检查"
            sleep 5
          done
          echo "INFO: ClickHouse 连接测试通过"
      containers:
      - name: apo-backend
        image: "{{ tpl .Values.apoBackend.image.repository . }}:{{ default .Chart.AppVersion .Values.apoBackend.image.tag }}"
        imagePullPolicy: {{ tpl .Values.apoBackend.image.pullPolicy . }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
            {{- toYaml .Values.apoBackend.resources | nindent 12 }}
        volumeMounts:
        - name: apo-backend-config
          mountPath: /app/config/apo.yml
          subPath: apo.yml
        {{- if .Values.persistence.enabled }}
        - name: sqlite-storage
          mountPath: /var/sqlite
        {{- end }}
      - name: polaris-analyzer
        image: "{{ tpl .Values.apoPolarisAnalyzer.image.repository . }}:{{ .Values.apoPolarisAnalyzer.image.tag }}"
        imagePullPolicy: {{ tpl .Values.apoBackend.image.pullPolicy . }}
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        env:
        - name: PROMETHEUS_ADDRESS
          value: "{{ tpl .Values.config.victoriaMetricsUrl . }}"
        - name: PROMETHEUS_STORAGE
          value: vm
        resources:
            {{- toYaml .Values.apoPolarisAnalyzer.resources | nindent 12 }}
        volumeMounts:
        - name: apo-backend-config
          mountPath: /app/config/
      volumes:
      - name: apo-backend-config
        configMap:
          name: {{ include "apo-backend.fullname" . }}-config
          defaultMode: 420
      {{- if .Values.persistence.enabled }}
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: {{ include "apo-backend.fullname" . }}-pvc
      {{- end }}