{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apo-backend.fullname" . }}-pvc
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if ( tpl .Values.persistence.storageClass . ) }}
  storageClassName: {{ tpl .Values.persistence.storageClass . }}
  {{- end }}
{{- end }}
