apiVersion: v1
kind: Service
metadata:
  name: apo-polaris-analyzer-svc
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
spec:
  ports:
    - name: metric
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    {{- include "apo-backend.selectorLabels" . | nindent 4 }}
  type: ClusterIP
