apiVersion: v1
kind: Service
metadata:
  name: {{ include "apo-backend.fullname" . }}-svc
  labels:
    {{- include "apo-backend.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "apo-backend.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
