global:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  language: en
  baseURL: ""

api:
  image:
    repository: docker.io/clouddetail/apo-dify-api
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"

pluginDaemon:
  image:
    repository: docker.io/clouddetail/dify-plugin-daemon
    pullPolicy: IfNotPresent
    tag: "0.0.3-local"

postgres:
  image:
    repository: docker.io/clouddetail/postgres
    pullPolicy: IfNotPresent
    tag: "15-alpine"

sandbox:
  image:
    repository: docker.io/clouddetail/dify-sandbox
    pullPolicy: IfNotPresent
    tag: "0.2.10"

ssrf:
  image:
    repository: docker.io/clouddetail/ubuntu-squid
    pullPolicy: IfNotPresent
    tag: "6.6-24.04_edge"

web:
  image:
    repository: docker.io/clouddetail/apo-dify-web
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"

worker:
  image:
    repository: docker.io/clouddetail/apo-dify-api
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"

nodeSelector: {}
tolerations: []
affinity: {}

hostPath: "/data/apo/dify"
