global:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  language: en
  baseURL: ""

api:
  initImage:
    repository: docker.io/clouddetail/apo-init-postgres
    pullPolicy: IfNotPresent
    tag: "v1.0.0"
  image:
    repository: docker.io/clouddetail/apo-dify-api
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"
  persistent:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: ""
    size: 10Gi

pluginDaemon:
  initImage:
    repository: docker.io/clouddetail/apo-init-postgres
    pullPolicy: IfNotPresent
    tag: "v1.0.0"
  image:
    repository: docker.io/clouddetail/dify-plugin-daemon
    pullPolicy: IfNotPresent
    tag: "0.0.3-local"
  persistent:
    enabled: true
    accessModes:
      - ReadWriteOnce
    storageClass: ""
    size: 10Gi

sandbox:
  image:
    repository: docker.io/clouddetail/dify-sandbox
    pullPolicy: IfNotPresent
    tag: "0.2.10"

ssrf:
  image:
    repository: docker.io/clouddetail/ubuntu-squid
    pullPolicy: IfNotPresent
    tag: "6.6-24.04_edge"

web:
  image:
    repository: docker.io/clouddetail/apo-dify-web
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"

worker:
  image:
    repository: docker.io/clouddetail/apo-dify-api
    pullPolicy: IfNotPresent
    tag: "v1.0.0-1"

nodeSelector: {}
tolerations: []
affinity: {}
