apiVersion: v1
kind: Service
metadata:
  name: {{ include "apo-nginx-proxy.fullname" . }}-svc
  labels:
    {{- include "apo-nginx-proxy.labels" . | nindent 4 }}
spec:
  ports:
  {{- $serviceType := .Values.service.type -}}
  {{- range .Values.service.ports }}
  - name: {{ tpl .name $ }}
    port: {{ tpl (toString .port) $ }}
    targetPort: {{ tpl (toString .targetPort) $ }}
    protocol: {{ tpl .protocol $ }}
  {{- end }}
  selector:
    {{- include "apo-nginx-proxy.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.service.type }}"
