apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apo-dify-api
  labels:
    app.kubernetes.io/instance: apo-dify-api
    app: apo-dify-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: apo-dify-api
  selector:
    matchLabels:
      app: apo-dify-api
  template:
    metadata:
      labels:
        app: apo-dify-api
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: dify-api-storage
        hostPath:
          path: {{ .Values.hostPath }}/app/api/storage
          type: DirectoryOrCreate
      containers:
      - name: dify-api
        image: "{{ tpl .Values.api.image.repository . }}:{{ tpl .Values.api.image.tag . }}"
        env:
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: '15'
        - name: REFRESH_TOKEN_EXPIRE_DAYS
          value: '2'
        - name: MODE
          value: api
        - name: LOG_LEVEL
          value: DEBUG
        - name: SECRET_KEY
          value: "sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U"
        - name: CONSOLE_WEB_URL
          value: ""
        - name: INIT_PASSWORD
          value: password
        - name: CONSOLE_API_URL
          value: "{{ tpl .Values.global.baseURL . }}/dify"
        - name: SERVICE_API_URL
          value: "{{ tpl .Values.global.baseURL . }}/dify"
        - name: APP_WEB_URL
          value: "{{ tpl .Values.global.baseURL . }}/dify"
        - name: FILES_URL
          value: "{{ tpl .Values.global.baseURL . }}/dify"
        - name: APO_BACKEND_URL
          value: "{{ tpl .Values.global.baseURL . }}"
        - name: MIGRATION_ENABLED
          value: "true"
        - name: DB_USERNAME
          value: {{ .Values.global.postgres.username }}
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: pg-username
        - name: DB_PASSWORD
          value: {{ .Values.global.postgres.password }}
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: pg-password
        - name: DB_HOST
          value: {{ .Values.global.postgres.host }}
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: pg-host
        - name: DB_PORT
          value: '{{ .Values.global.postgres.port }}'
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: pg-port
        - name: DB_DATABASE
          value: {{ .Values.global.postgres.apoDifyDatabase }}
        - name: REDIS_HOST
          value: apo-dify-redis-svc
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: redis-host
        - name: REDIS_PORT
          value: '6379'
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: redis-port
          # default redis username is empty
        - name: REDIS_USERNAME
          value: ''
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: redis-username
        - name: REDIS_PASSWORD
          value: difyai123456
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: redis-password
        - name: REDIS_USE_SSL
          value: "false"
        - name: REDIS_DB
          value: "0"
        - name: CELERY_BROKER_URL
          value: >-
            redis://$(REDIS_USERNAME):$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1
        - name: WEB_API_CORS_ALLOW_ORIGINS
          value: "*"
        - name: CONSOLE_CORS_ALLOW_ORIGINS
          value: "*"
        - name: STORAGE_TYPE
          value: opendal
        - name: OPENDAL_SCHEME
          value: fs
        - name: OPENDAL_FS_ROOT
          value: storage
        - name: STORAGE_LOCAL_PATH
          value: /app/api/storage
        - name: VECTOR_STORE
          value: weaviate
        - name: WEAVIATE_HOST
          value: apo-dify-weaviate-svc
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: weaviate-host
        - name: WEAVIATE_PORT
          value: '8080'
          # valueFrom:
          #   secretKeyRef:
          #     name: dify-credentials
          #     key: weaviate-port
        - name: WEAVIATE_ENDPOINT
          value: http://$(WEAVIATE_HOST):$(WEAVIATE_PORT)
        - name: WEAVIATE_API_KEY
          value: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
        - name: CODE_EXECUTION_ENDPOINT
          value: http://apo-dify-sandbox-svc:8194
        - name: CODE_EXECUTION_API_KEY
          value: dify-sandbox
        - name: CODE_MAX_NUMBER
          value: "9223372036854775807"
        - name: CODE_MIN_NUMBER
          value: "-9223372036854775808"
        - name: CODE_MAX_STRING_LENGTH
          value: "80000"
        - name: TEMPLATE_TRANSFORM_MAX_LENGTH
          value: "80000"
        - name: CODE_MAX_STRING_ARRAY_LENGTH
          value: "30"
        - name: CODE_MAX_OBJECT_ARRAY_LENGTH
          value: "30"
        - name: CODE_MAX_NUMBER_ARRAY_LENGTH
          value: "1000"
        - name: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
          value: "1000"
          # uncommect to enable SSRF
        - name: SSRF_PROXY_HTTP_URL
          value: 'http://apo-dify-ssrf-svc:3128'
        - name: SSRF_PROXY_HTTPS_URL
          value: 'http://apo-dify-ssrf-svc:3128'
        - name: SENTRY_DSN
          value: ''
        - name: SENTRY_TRACES_SAMPLE_RATE
          value: '1.0'
        - name: SENTRY_PROFILES_SAMPLE_RATE
          value: '1.0'
          # plugin settings
        - name: 'PLUGIN_MAX_PACKAGE_SIZE'
          value: '52428800'
        - name: 'INNER_API_KEY_FOR_PLUGIN'
          value: 'QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1'
        - name: 'PLUGIN_DAEMON_KEY'
          value: 'lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi'
        - name: 'PLUGIN_DAEMON_URL'
          value: 'http://apo-dify-plugin-daemon-svc:5002'
        - name: 'MARKETPLACE_ENABLED'
          value: 'true'
        - name: 'MARKETPLACE_API_URL'
          value: 'https://marketplace.dify.ai'
        startupProbe:
            exec:
              command:
                - flask
                - db
                - upgrade
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 100
            timeoutSeconds: 60
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 3000m
            memory: 2Gi
        ports:
        - containerPort: 5001
        imagePullPolicy: {{ tpl .Values.api.image.pullPolicy . }}
        volumeMounts:
        - name: dify-api-storage
          mountPath: /app/api/storage
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- else if .Values.global.affinity }}
      {{- with .Values.global.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
