apiVersion: v1
kind: Service
metadata:
  name: apo-dify-api-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30051
    protocol: TCP
    name: apo-dify-api
  type: NodePort
  selector:
    app: apo-dify-api
