kind: Service
apiVersion: v1
metadata:
  name: apo-dify-nginx-nodeport-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: apo-dify-nginx
  type: NodePort
  ports:
  - name: apo-dify-nginx
    port: 80
    targetPort: 80
    nodePort: 30000
