apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-hostpath"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- else if .Values.global.affinity }}
      {{- with .Values.global.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: init-hostpath
        image: "{{ tpl .Values.initHostPath.image.repository . }}:{{ tpl .Values.initHostPath.image.tag . }}"
        command: ['sh', '-c', 'tar -zxvf /data/${LANGUAGE}/apo.tgz && cp -r /data/apo/dify/* /mnt/hostpath/']
        env:
        - name: LANGUAGE
          value: "{{ .Values.global.language }}"
        volumeMounts:
        - name: hostpath-volume
          mountPath: /mnt/hostpath
      volumes:
      - name: hostpath-volume
        hostPath:
          path: {{ .Values.hostPath }}
          type: DirectoryOrCreate
