apiVersion: v1
kind: Service
metadata:
  name: apo-dify-redis-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: apo-dify-redis
  type: ClusterIP
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
