apiVersion: v1
kind: Service
metadata:
  name: apo-dify-sandbox-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: dify-sandbox
  type: ClusterIP
  selector:
    app: apo-dify-sandbox
