apiVersion: v1
kind: Service
metadata:
  name: apo-dify-weaviate-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: apo-dify-weaviate
  type: ClusterIP
  ports:
  - name: weaviate
    protocol: TCP
    port: 8080
    targetPort: 8080
