{
 "title": "集群总览",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "label": "精度", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(node_cpu_seconds_total{cluster=\"$cluster\"},job_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群总CPU使用率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])))",
     "legendFormat": "Real Linux"
    }
   ]
  },
  {
   "title": "集群总内存使用率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\", job_name=\"$job_name\"}) / sum(max_over_time(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"}[5m]))",
     "legendFormat": "Real Linux"
    }
   ]
  },
  {
   "title": "命名空间数量",
   "type": "stat",
   "description": "命名空间数量(Namespaces)",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (namespace) (container_memory_rss))"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "description": "节点数(Node)",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by (instance_name) (container_memory_rss))"
    }
   ]
  },
  {
   "title": "CPU使用量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(max_over_time(machine_cpu_cores{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "stat",
   "description": "内存使用量(RAM Usage)",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\", job_name=\"$job_name\"})",
     "legendFormat": "Real Linux"
    },
    {
     "expr": "sum(max_over_time(machine_memory_bytes{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "运行的Pod数",
   "type": "stat",
   "description": "运行的Pod数(Running Pod)",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(group by (pod) (container_memory_rss))"
    }
   ]
  },
  {
   "title": "集群CPU使用率",
   "type": "timeseries",
   "description": "集群CPU使用率 (Cluster CPU Utilization)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])))",
     "legendFormat": "Linux"
    },
    {
     "expr": "1 - avg(rate(windows_cpu_time_total{cluster=\"$cluster\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "集群内存使用率",
   "type": "timeseries",
   "description": "集群内存使用率(Cluster Memory Utilization)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\", job_name=\"$job_name\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"})",
     "legendFormat": "Linux"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{cluster=\"$cluster\"} - windows_memory_available_bytes{cluster=\"$cluster\"}) / sum(windows_os_visible_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Windows"
    }
   ]
  },
  {
   "title": "集群整体网络带宽(按设备统计)",
   "type": "timeseries",
   "description": "设备的网络利用率(Global Network Utilization by device),移除了常见的虚拟设备以避免噪音(veth,azv,lxc,cali)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|cali).*\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (device)",
     "legendFormat": "接收 : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|cali).*\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (device)",
     "legendFormat": "发送 : {{ device }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{cluster=\"$cluster\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Received : {{ nic }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{cluster=\"$cluster\"}[$__rate_interval])) by (nic)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "网络饱和 - 丢包数",
   "type": "timeseries",
   "description": "网络饱和 - 丢包数(Network Saturation - Packets Dropped)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval]))",
     "legendFormat": "Linux Packets dropped (transmit)"
    },
    {
     "expr": "sum(rate(windows_net_packets_received_discarded_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(windows_net_packets_outbound_discarded_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Windows Packets dropped (transmit)"
    }
   ]
  },
  { "title": "节点资源使用", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "节点CPU使用率",
   "type": "timeseries",
   "description": "节点CPU使用率(CPU Utilization by instance)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance_name, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval]))) by (instance_name)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "avg(sum by (instance_name,core) (rate(windows_cpu_time_total{mode!=\"idle\", cluster=\"$cluster\"}[$__rate_interval]))) by (instance_name)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "节点内存使用量",
   "type": "timeseries",
   "description": "节点内存使用量(Memory Utilization by instance)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\", job_name=\"$job_name\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\", job_name=\"$job_name\"}) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    },
    {
     "expr": "sum(windows_os_visible_memory_bytes{cluster=\"$cluster\"} - windows_memory_available_bytes{cluster=\"$cluster\"}) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  {
   "title": "节点的网络使用量",
   "type": "timeseries",
   "description": "节点的网络使用量(Total Network Received with all virtual devices by instance), 含虚拟设备和回环网卡",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "接收: {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "发送: {{ instance_name }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{cluster=\"$cluster\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{cluster=\"$cluster\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "节点的网络使用量(不含回环/虚拟设备)",
   "type": "timeseries",
   "description": "节点的网络使用量,不含回环/虚拟设备(Network Received without loopback by instance)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo|cali).*\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo|cali).*\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    },
    {
     "expr": "sum(rate(windows_net_bytes_received_total{nic!~\".*Virtual.*\",cluster=\"$cluster\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(windows_net_bytes_sent_total{nic!~\".*Virtual.*\",cluster=\"$cluster\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "节点的网络使用量(仅回环)",
   "type": "timeseries",
   "description": "节点(Network Received (loopback only) by instance)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Received bytes in {{ instance_name }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\", cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "Transmitted bytes in {{ instance_name }}"
    }
   ]
  },
  {
   "title": "节点CPU限流时长",
   "type": "timeseries",
   "description": "节点CPU限流时长(CPU Core Throttled by instance), 没数据说明CPU充足或未做限制",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{cluster=\"$cluster\", job_name=\"$job_name\"}[$__rate_interval])) by (instance_name)",
     "legendFormat": "{{ instance_name }}"
    }
   ]
  },
  { "title": "命名空间资源使用", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "命名空间的CPU使用量",
   "type": "timeseries",
   "description": "命名空间的CPU使用量(CPU Utilization by namespace)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (namespace) OR (group by (namespace) (container_memory_rss{job_name=\"$container_metric_source\",cluster=\"$cluster\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "命名空间的CPU限流时长",
   "type": "timeseries",
   "description": "命名空间的CPU限流时长(CPU Throttled seconds by namespace), 没数据说明没有被限制,意味着CPU充足或者未进行限制",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\", cluster=\"$cluster\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "命名空间的网络使用量",
   "type": "timeseries",
   "description": "命名空间的网络使用量(Network Received by namespace)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace!=\"\"}[$__rate_interval])) by (namespace)\nOR (group by (namespace) (container_memory_rss{job_name=\"$container_metric_source\",cluster=\"$cluster\"}) * 0 ) ",
     "legendFormat": "接收 : {{ namespace }}"
    },
    {
     "expr": "- (sum(rate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace!=\"\"}[$__rate_interval])) by (namespace)\nOR (group by (namespace) (container_memory_rss{job_name=\"$container_metric_source\",cluster=\"$cluster\"}) * 0 ) )",
     "legendFormat": "发送 : {{ namespace }}"
    }
   ]
  },
  {
   "title": "命名空间的内存使用量",
   "type": "timeseries",
   "description": "命名空间的内存使用量(Memory Utilization by namespace)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", cluster=\"$cluster\"}) by (namespace)\n OR (group by (namespace) (container_memory_rss{job_name=\"$container_metric_source\",cluster=\"$cluster\"}) * 0 ) ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}