{
 "title": "基础设施情况",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   {
    "name": "container_metric_source",
    "label": "容器指标数据源",
    "query": "integrations/kubernetes/cadvisor"
   },
   { "name": "node_metric_source", "label": "主机指标数据源", "query": "integrations/unix" },
   {
    "name": "agent_metric_source",
    "query": "prometheus.scrape.agent_metrics"
   },
   { "name": "service_type", "label": "查询方式", "query": "按K8s查询 : .*, 按虚机查询 :  ," },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "query_result(group by (namespace) (container_memory_rss{job_name=\"$container_metric_source\",namespace=~\"$service_type\"}))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(group by (pod) (container_memory_rss{namespace=\"$namespace\",job_name=\"$container_metric_source\"}))"
    }
   },
   {
    "name": "service_name",
    "label": "应用名",
    "query": {
     "query": "query_result(group by (svc_name) (kindling_span_trace_duration_nanoseconds_count{vm=\"$service_type\"}) or group by (svc_name) (kindling_span_trace_duration_nanoseconds_count{pod=~\"$pod\",namespace=~\"$namespace\"}))"
    }
   },
   {
    "name": "related_nodes",
    "label": "相关节点",
    "query": {
     "query": "query_result( group by (instance_name) (container_memory_rss{job_name=\"integrations/kubernetes/cadvisor\",pod=~\"$pod\",pod!=\"\"}) or group by (instance_name) ( label_replace(kindling_span_trace_duration_nanoseconds_count{svc_name=\"$service_name\",svc_name!=\"\"},\"instance_name\", \"$1\", \"node_name\", \"(.+)\" )))"
    }
   },
   {
    "name": "resolution",
    "label": "精度",
    "query": "1s, 15s, 30s, 1m, 3m, 5m , 10m, 30m"
   },
   {
    "name": "container_metric_source",
    "label": "容器指标数据源",
    "query": "integrations/kubernetes/cadvisor"
   },
   {
    "name": "related_pid",
    "query": {
     "query": "label_values(kindling_span_trace_duration_nanoseconds_count{svc_name=~\"$service_name\"},pid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "容器CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "容器CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      }
     ]
    },
    {
     "title": "容器CPU节流时间",
     "type": "timeseries",
     "description": "容器CPU节流时间(CPU Throttled seconds),没有数据说明CPU充足或者未做限制",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval])) by (container,pod)",
       "legendFormat": "{{pod}}:{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器内存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "容器内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}) by (container,pod)",
       "legendFormat": "{{pod}}: {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器磁盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "读写字节数 /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "读写花费时间 /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_read_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_write_seconds_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    },
    {
     "title": "读写次数 /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod,container)(rate(container_fs_reads_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Read {{pod}}:{{container}}"
      },
      {
       "expr": "- sum by (pod,container)(rate(container_fs_writes_total{namespace=\"$namespace\", pod=~\"$pod\", image!=\"\", container!=\"\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Write {{pod}}:{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器网络",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "与下游服务RTT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kindling_network_rtt{src_namespace=\"$namespace\", src_pod=~\"$pod\"}",
       "legendFormat": "{{src_pod}} -> {{dst_pod}} ({{dst_ip}})"
      }
     ]
    },
    {
     "title": "与下游服务RTT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kindling_network_rtt{src_namespace=\"$namespace\", src_pod=~\"$pod\"}",
       "legendFormat": "{{src_pod}} -> {{dst_pod}} ({{dst_ip}})"
      }
     ]
    },
    {
     "title": "网络带宽使用",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "接收"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "发送"
      }
     ]
    },
    {
     "title": "包传输速率",
     "type": "timeseries",
     "description": "每秒钟收发的包数量  1 p/s = 1000 mp/s",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "接收"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "发送"
      }
     ]
    },
    {
     "title": "丢包数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_packets_dropped_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "Transmitted"
      }
     ]
    },
    {
     "title": "网络错误包数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "接收"
      },
      {
       "expr": "- sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\", pod=~\"$pod\", job_name=\"$container_metric_source\"}[$__rate_interval]))",
       "legendFormat": "发送"
      }
     ]
    }
   ]
  },
  { "title": "应用网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "与下游服务RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kindling_network_rtt{node_name=~\"$related_nodes\", pid=~\"$related_pid\"}",
     "legendFormat": "{{src_pod}} ({{src_ip}}) -> {{dst_pod}} ({{dst_ip}}) "
    }
   ]
  },
  { "title": "$related_nodes - 宿主机状态总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "related_nodes" },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "System - 在内核中运行的系统进程"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "User - 在用户空间运行的用户程序"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"nice\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Nice - 在用户空间下执行的Niced进程"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Iowait - IO等待时间"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Softirq - 处理软中断"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Steal - 在虚拟化环境中运行时，在其他操作系统上花费的时间"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}) by (cpu)))",
     "legendFormat": "Idle - 空闲时间"
    }
   ]
  },
  {
   "title": "内存使用情况",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_MemFree_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_Buffers_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_Cached_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_Slab_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_PageTables_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_SwapCached_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "App - 用户空间应用使用量"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "PageTables - 用于在虚拟和物理内存地址之间映射的内存"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "SwapCache - 跟踪已从交换中提取但尚未修改的页面的内存"
    },
    {
     "expr": "node_memory_Slab_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "Slab - 内核用于缓存数据结构以供自己使用的内存 (缓存，如inode，dentry等)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "Cache - 打开的文件缓存"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "Buffers - 块设备 (如硬盘) 缓存"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "Unused - 未分配内存"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"} - node_memory_SwapFree_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"})",
     "legendFormat": "Swap - 已使用的Swap空间"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "Hardware Corrupted - 内核标识为损坏/不工作的RAM量"
    }
   ]
  },
  {
   "title": "网络传输速率(无虚拟和回环网卡)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "文件描述符打开数",
   "type": "timeseries",
   "description": "文件描述符打开数(File Descriptor)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "最大限制"
    },
    {
     "expr": "node_filefd_allocated{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\"}",
     "legendFormat": "当前值"
    }
   ]
  },
  {
   "title": "磁盘操作数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - 读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - 写入"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - 读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - 写入"
    }
   ]
  },
  {
   "title": "文件系统空闲空间",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - 空闲大小"
    },
    {
     "expr": "node_filesystem_size_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}} - 总大小"
    }
   ]
  },
  {
   "title": "磁盘使用量",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device!~'rootfs'} - node_filesystem_avail_bytes{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "I/O 利用率",
   "type": "timeseries",
   "description": "系统在特定时间段内用于处理 I/O 操作的时间占总时间的比例,反映了系统在处理 I/O 任务时的繁忙程度",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance_name=~\"${related_nodes}\",job_name=\"$node_metric_source\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}