nameOverride: ""
replicas: "1"
hostNetwork: "false"
dnsPolicy: "ClusterFirst"

initImage:
  repository: registry.cn-hangzhou.aliyuncs.com/kindlingx/busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.36.1"

apoBackend:
  image:
    registry: registry.cn-hangzhou.aliyuncs.com/kindlingx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
apoPolarisAnalyzer:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/kindlingx/polaris-analyzer
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: NodePort
  nodePort: 31363

config:
  clickhouseUrl: "apo-clickhouse-svc:9000"
  clickhouseUsername: "admin"
  clickhousePassword: "WPKf-e9U.X)K)ezTDo9#"

persistence:
  enabled: false
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

nodeSelector: {}
affinity: {}
tolerations: []
