apiVersion: v1
kind: ConfigMap
metadata:
  name: apo-apm-adapter-config
  labels:
    {{- include "apo-collector.labels" . | nindent 4 }}
data:
  apm-adapter.yml: |
    {{ toYaml .Values.apoApmAdapter.config | nindent 4 }}
