apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: odigos-webhook
  name: apo-odigos-webhook-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
      - protocol: TCP
        port: 443
        targetPort: 9443
  selector:
    app.kubernetes.io/name: odigos-instrumentor