{{- if has "trace" .Values.global.agentCollectorMode }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: odigos-instrumentor
  name: apo-odigos-instrumentor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: odigos-instrumentor
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: odigos-instrumentor
    spec:
      containers:
      - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
        command:
          - /odigos-instrumentor
        {{- if .Values.imagePrefix }}
        image: "{{ .Values.imagePrefix }}/{{ tpl .Values.instrumentor.image.repository . }}:{{ .Values.instrumentor.image.tag }}"
        {{- else }}
        image: "{{ tpl .Values.instrumentor.image.repository . }}:{{ .Values.instrumentor.image.tag }}"
        {{- end }}
        imagePullPolicy: "{{ tpl .Values.instrumentor.image.imagePullPolicy . }}"
        env:
          - name: OTEL_SERVICE_NAME
            value: instrumentor
          - name: CURRENT_NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ENABLE_CUSTOM_COLLECTOR
            value: 'true'
        envFrom:
          - configMapRef:
              name: apo-odigos-own-telemetry-otel-config
              optional: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        resources:
          {{- toYaml .Values.instrumentor.resources | nindent 10 }}
        volumeMounts:
        - name: setup-cfg
          readOnly: true
          mountPath: /config
        - name: cert
          readOnly: true
          mountPath: /tmp/k8s-webhook-server/serving-certs
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: setup-cfg
        configMap:
          name: apo-instrumentor-config
          defaultMode: 420
      - name: cert
        secret:
          secretName: apo-odigos-webhook-certs
          defaultMode: 420
      securityContext:
        runAsNonRoot: true
      serviceAccountName: odigos-instrumentor
      terminationGracePeriodSeconds: 10
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
      {{- if .Values.instrumentor.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.instrumentor.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.instrumentor.affinity }}
      {{- with .Values.instrumentor.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- else if .Values.global.affinity }}
      {{- with .Values.global.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.instrumentor.tolerations }}
      tolerations:
{{ toYaml .Values.instrumentor.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
{{- end }}