name: Release Charts

on:
  push:
    branches:
      - main
      - test-action

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Agent chart
        run: |
          cp -rf charts/apo-one-agent charts/apo/charts/

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
          access-key-id: "${{ secrets.ALIYUN_OSS_ACCESS_KEY }}"
          access-key-secret: "${{ secrets.ALIYUN_OSS_SECRETS_KEY }}"

      - name: Sync Helm index to Aliyun OSS
        run: |
          curl -o index.current https://apo-charts.oss-cn-hangzhou.aliyuncs.com/index.yaml||true
          helm repo index .cr-release-packages/ --url https://apo-charts.oss-cn-hangzhou.aliyuncs.com/ --merge index.current
          ossutil cp -rf .cr-release-packages/index.yaml oss://apo-charts/
          for file in $(ls  .cr-release-packages/apo-*.tgz)
            do 
               ossutil cp -rf $file oss://apo-charts/
            done
