name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: Secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy Agent chart
        run: |
          cp -rf charts/apo-one-agent charts/apo/charts/

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - uses: hhyasdf/image-sync-action@v1.1
        with:
          auth_file: ./image-sync/auth.yaml # The auth information file of registries, optional.
          images_file: ./image-sync/images.yaml # The images file descirbes which images need to sync, always needed.
          version: latest # The version of image-syncer, use the latest version if not specified.
          proc: 5 # The number of concurrent processes, default is 5.
        env:
          DOCKERHUB_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_REGISTRY_USERNAME }}
          DOCKERHUB_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_REGISTRY_PASSWORD }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Check no chart changes
        run: |
          if compgen -G ".cr-release-packages/apo-*.tgz" > /dev/null; then
            echo "Chart changes, continuing workflow..."
            echo "chartChangeFlag=0" >> $GITHUB_ENV
          else
            echo "No chart changes, exiting successfully."
            echo "chartChangeFlag=1" >> $GITHUB_ENV
          fi

      - name: Install aliyun ossutil
        if: ${{ env.chartChangeFlag == '0' }}
        run: |
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
          ossutil config -e https://oss-cn-hangzhou.aliyuncs.com -i ${{ secrets.ALIYUN_OSS_ACCESS_KEY }} -k ${{ secrets.ALIYUN_OSS_SECRETS_KEY }} -L CH

      - name: Sync Helm index to Aliyun OSS
        if: ${{ env.chartChangeFlag == '0' }}
        run: |
          curl -o index.current https://apo-charts.oss-cn-hangzhou.aliyuncs.com/index.yaml||true
          helm repo index .cr-release-packages/ --url https://apo-charts.oss-cn-hangzhou.aliyuncs.com/ --merge index.current
          ossutil cp -rf .cr-release-packages/index.yaml oss://apo-charts/
          for file in $(ls  .cr-release-packages/apo-*.tgz)
            do 
               ossutil cp -rf $file oss://apo-charts/
            done
